language: python
python:
  - "3.9"
# command to install dependencies
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - "pip install coverage"
  - "pip install coveralls"
install:
  - pip install -r requirements.txt
  env:
  global:
    - CODECOV_TOKEN=<c674785f-3749-406d-8e21-a1cf691da440>

# command to run tests
script:
  - "coverage run --source 'src' -m pytest"
after_success:
  coveralls
